import { z } from "zod";

const totpCodeSchema = z
  .string()
  .length(6, "TOTP code must be exactly 6 digits")
  .regex(/^\d{6}$/, "TOTP code must contain only digits")
  .describe(
    "6-digit numeric Time-based One-Time Password (TOTP) generated by an authenticator app (e.g. Google Authenticator, Authy). Valid for a 30-second window.",
  );

const backupCodeSchema = z
  .string()
  .regex(
    /^[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$/,
    "Invalid backup code format. Expected format: XXXX-XXXX-XXXX",
  )
  .describe(
    "Single-use backup recovery code in XXXX-XXXX-XXXX format (alphanumeric, uppercase). Provided to the user during 2FA setup. Consumed and invalidated upon use.",
  );

export const VerifySetupSchema = z
  .object({
    totpCode: totpCodeSchema,
  })
  .describe(
    "Confirms that the user's authenticator app is correctly configured by verifying a live TOTP code before 2FA is fully activated on the account.",
  );

export const VerifyTwoFactorSchema = z
  .object({
    userId: z
      .string()
      .uuid("Invalid user ID format")
      .describe(
        "UUID of the user completing the second factor challenge. Returned in the first-step login response (HTTP 202) when 2FA is required.",
      ),
    totpCode: totpCodeSchema
      .optional()
      .describe(
        "TOTP code from the user's authenticator app. Either totpCode or backupCode must be supplied — not both.",
      ),
    backupCode: backupCodeSchema
      .optional()
      .describe(
        "One-time backup recovery code. Use only if the authenticator app is unavailable. Either backupCode or totpCode must be supplied — not both.",
      ),
  })
  .refine((data) => data.totpCode || data.backupCode, {
    message: "Either totpCode or backupCode is required",
  })
  .describe(
    "Second-factor verification payload. The user must supply exactly one of: a live TOTP code from their authenticator app, or a single-use backup recovery code.",
  );

export const DisableTwoFactorSchema = z
  .object({
    password: z
      .string()
      .min(1, "Password is required")
      .describe(
        "Current account password. Required to re-authenticate before 2FA can be disabled, preventing unauthorised deactivation.",
      ),
    totpCode: totpCodeSchema.describe(
      "A current TOTP code from the authenticator app, confirming device possession before 2FA is turned off.",
    ),
  })
  .describe(
    "Request body for disabling two-factor authentication. Both the account password and a valid TOTP code are required as dual confirmation.",
  );

export const RegenerateBackupCodesSchema = z
  .object({
    totpCode: totpCodeSchema.describe(
      "A current TOTP code confirming authenticator app access before new backup codes are generated. The old codes are invalidated immediately upon regeneration.",
    ),
  })
  .describe(
    "Request body for regenerating two-factor backup codes. Requires a valid TOTP code. All previously issued backup codes are immediately invalidated.",
  );

export type VerifySetupInput = z.infer<typeof VerifySetupSchema>;
export type VerifyTwoFactorInput = z.infer<typeof VerifyTwoFactorSchema>;
export type DisableTwoFactorInput = z.infer<typeof DisableTwoFactorSchema>;
export type RegenerateBackupCodesInput = z.infer<typeof RegenerateBackupCodesSchema>;
